#pragma once

#include <stdint.h>

namespace pypilot_data_model {

enum class FieldId : uint16_t {
    unknown = 0,

    server_version,
    server_hostname,
    server_config_dir,
    server_profile_name,
    server_enabled,
    server_persistent,
    server_watchdog_enabled,
    server_timestamp_s,
    server_uptime_s,
    server_monotonic_s,
    server_poll_period_s,
    server_client_count,
    server_value_count,
    server_watch_count,

    status_health,
    status_faults,
    status_warnings,
    status_uptime_s,
    status_loop_period_s,
    status_cpu_load_0_1,
    status_free_memory_bytes,
    status_last_error,
    status_last_warning,

    ap_enabled,
    ap_mode,
    ap_preferred_mode,
    ap_pilot,
    ap_heading_deg,
    ap_heading_command_deg,
    ap_heading_error_deg,
    ap_heading_error_int_deg,
    ap_heading_command_rate_deg_s,
    ap_runtime_s,

    ap_tack_enabled,
    ap_tack_state,
    ap_tack_direction,
    ap_tack_timeout_s,
    ap_tack_delay_s,
    ap_tack_angle_deg,
    ap_tack_rate_deg_s,
    ap_tack_progress_0_1,
    ap_tack_command_heading_deg,
    ap_tack_start_heading_deg,
    ap_tack_target_heading_deg,

    pilot_command_source,
    pilot_command_heading_deg,
    pilot_command_heading_rate_deg_s,
    pilot_command_servo_norm,
    pilot_command_servo_position_deg,
    pilot_output_command_norm,
    pilot_output_heading_error_deg,
    pilot_output_desired_heading_deg,
    pilot_output_desired_heading_rate_deg_s,
    pilot_output_saturated_command_norm,
    pilot_output_feed_forward_norm,
    pilot_output_proportional_norm,
    pilot_output_derivative_norm,
    pilot_output_integral_norm,
    pilot_output_saturated,
    pilot_output_fault,
    pilot_output_active_name,

    imu_state_enabled,
    imu_state_present,
    imu_state_healthy,
    imu_state_device,
    imu_state_driver,
    imu_state_rate_hz,
    imu_state_dt_s,
    imu_state_sample_count,
    imu_state_drop_count,
    imu_state_error_count,

    imu_calibration_state,
    imu_calibration_accel_valid,
    imu_calibration_compass_valid,
    imu_calibration_gyro_valid,
    imu_calibration_heading_offset_deg,
    imu_calibration_compass_field_strength,
    imu_calibration_compass_inclination_deg,
    imu_calibration_progress_0_1,

    imu_heading_deg,
    imu_heading_lowpass_deg,
    imu_headingrate_deg_s,
    imu_headingrate_lowpass_deg_s,
    imu_headingraterate_deg_s2,
    imu_headingraterate_lowpass_deg_s2,
    imu_pitch_deg,
    imu_roll_deg,
    imu_heel_deg,
    imu_pitchrate_deg_s,
    imu_rollrate_deg_s,
    imu_fusion_q_pose,

    wind_source,
    wind_direction_deg,
    wind_speed_kn,
    wind_filtered_direction_deg,
    wind_filtered_speed_kn,
    wind_offset_deg,
    wind_sensors_height_m,
    wind_filter_constant_0_1,
    wind_filter_factor_0_1,

    truewind_source,
    truewind_direction_deg,
    truewind_speed_kn,
    truewind_filtered_direction_deg,
    truewind_filtered_speed_kn,
    truewind_offset_deg,
    truewind_sensors_height_m,
    truewind_filter_constant_0_1,
    truewind_filter_factor_0_1,

    gps_source,
    gps_timestamp_s,
    gps_track_deg,
    gps_speed_kn,
    gps_declination_deg,
    gps_compass_error_deg,

    apb_source,
    apb_track_deg,
    apb_xte_nmi,
    apb_xte_gain_deg_per_nmi,
    apb_mode_hint,
    apb_sender_id,

    rmb_source,
    rmb_xte_nmi,
    rmb_destination_lat_deg,
    rmb_destination_lon_deg,
    rmb_range_nmi,
    rmb_bearing_deg,
    rmb_closing_velocity_kn,
    rmb_arrived,

    water_speed_kn,
    water_leeway_deg,
    water_current_speed_kn,
    water_current_direction_deg,
    water_wind_speed_kn,
    water_wind_direction_deg,
    water_depth_m,
    water_depth_offset_m,

    rudder_angle_deg,
    rudder_speed_deg_s,
    rudder_offset_deg,
    rudder_scale_deg_per_raw,
    rudder_nonlinearity,
    rudder_range_deg,
    rudder_calibration_state,

    servo_command_norm,
    servo_position_command_deg,
    servo_current_a,
    servo_current_noise_a,
    servo_voltage_v,
    servo_controller_temp_c,
    servo_motor_temp_c,
    servo_engaged,
    servo_flags,
    servo_faults,
    servo_max_current_a,
    servo_period_s,
    servo_speed_norm,
    servo_position_deg,
    servo_duty_pct,
    servo_watts_w,
    servo_amp_hours_ah,

    servo_telemetry_state,
    servo_telemetry_command_norm,
    servo_telemetry_raw_command_norm,
    servo_telemetry_position_deg,
    servo_telemetry_position_command_deg,
    servo_telemetry_speed_norm,
    servo_telemetry_duty_pct,
    servo_telemetry_voltage_v,
    servo_telemetry_current_a,
    servo_telemetry_current_noise_a,
    servo_telemetry_watts_w,
    servo_telemetry_controller_temp_c,
    servo_telemetry_motor_temp_c,
    servo_telemetry_rudder_feedback_deg,
    servo_telemetry_packet_count,
    servo_telemetry_bad_packet_count,
    servo_telemetry_timeout_count,
    servo_telemetry_reboot_count,

    pilot_basic_P,
    pilot_basic_Pgain,
    pilot_basic_D,
    pilot_basic_Dgain,
    pilot_basic_DD,
    pilot_basic_DDgain,
    pilot_basic_PR,
    pilot_basic_PRgain,
    pilot_basic_FF,
    pilot_basic_FFgain,

    pilot_wind_gps_wind_offset_deg,
    pilot_wind_P,
    pilot_wind_Pgain,
    pilot_wind_D,
    pilot_wind_Dgain,
    pilot_wind_DD,
    pilot_wind_DDgain,
    pilot_wind_WG,
    pilot_wind_WGgain,

    pilot_absolute_P,
    pilot_absolute_Pgain,
    pilot_absolute_I,
    pilot_absolute_Igain,
    pilot_absolute_D,
    pilot_absolute_Dgain,
    pilot_absolute_FF,
    pilot_absolute_FFgain,

    pilot_rate_D,
    pilot_rate_Dgain,
    pilot_rate_DD,
    pilot_rate_DDgain,
    pilot_rate_FF,
    pilot_rate_FFgain,
    pilot_rate_maxturnrate_deg_s,
    pilot_rate_turnraterate_deg_s2,

    pilot_simple_P,
    pilot_simple_Pgain,
    pilot_simple_I,
    pilot_simple_Igain,
    pilot_simple_D,
    pilot_simple_Dgain,

    pilot_vmg_P,
    pilot_vmg_Pgain,
    pilot_vmg_D,
    pilot_vmg_Dgain,
    pilot_vmg_DD,
    pilot_vmg_DDgain,

    runtime_last_publish_period_s,
    runtime_published_value_count,
    runtime_dropped_value_count
};

} // namespace pypilot_data_model
