#pragma once

#include <stdint.h>

namespace pypilot_data_model {

enum class FieldId : uint16_t {
    unknown = 0,

    ap_enabled,
    ap_mode,
    ap_pilot,
    ap_heading_deg,
    ap_heading_command_deg,
    ap_heading_error_deg,
    ap_heading_error_int_deg,
    ap_heading_command_rate_deg_s,
    ap_runtime_s,

    imu_heading_deg,
    imu_heading_lowpass_deg,
    imu_headingrate_deg_s,
    imu_headingrate_lowpass_deg_s,
    imu_headingraterate_deg_s2,
    imu_headingraterate_lowpass_deg_s2,
    imu_pitch_deg,
    imu_roll_deg,
    imu_heel_deg,
    imu_pitchrate_deg_s,
    imu_rollrate_deg_s,
    imu_fusion_q_pose,

    wind_source,
    wind_direction_deg,
    wind_speed_kn,
    wind_filtered_direction_deg,
    wind_filtered_speed_kn,
    wind_offset_deg,
    wind_sensors_height_m,
    wind_filter_constant_0_1,
    wind_filter_factor_0_1,

    truewind_source,
    truewind_direction_deg,
    truewind_speed_kn,
    truewind_filtered_direction_deg,
    truewind_filtered_speed_kn,
    truewind_offset_deg,
    truewind_sensors_height_m,
    truewind_filter_constant_0_1,
    truewind_filter_factor_0_1,

    gps_source,
    gps_track_deg,
    gps_speed_kn,
    gps_declination_deg,
    gps_compass_error_deg,

    apb_source,
    apb_track_deg,
    apb_xte_nmi,
    apb_xte_gain_deg_per_nmi,
    apb_mode_hint,
    apb_sender_id,

    water_speed_kn,
    water_leeway_deg,
    water_current_speed_kn,
    water_current_direction_deg,
    water_wind_speed_kn,
    water_wind_direction_deg,

    rudder_angle_deg,
    rudder_speed_deg_s,
    rudder_offset_deg,
    rudder_scale_deg_per_raw,
    rudder_nonlinearity,
    rudder_range_deg,
    rudder_calibration_state,

    servo_command_norm,
    servo_position_command_deg,
    servo_current_a,
    servo_current_noise_a,
    servo_voltage_v,
    servo_controller_temp_c,
    servo_motor_temp_c,
    servo_engaged,
    servo_flags,
    servo_faults,
    servo_max_current_a,
    servo_period_s,
    servo_speed_norm,
    servo_position_deg,
    servo_duty_pct,
    servo_watts_w,
    servo_amp_hours_ah,

    pilot_basic_P,
    pilot_basic_Pgain,
    pilot_basic_D,
    pilot_basic_Dgain,
    pilot_basic_DD,
    pilot_basic_DDgain,
    pilot_basic_PR,
    pilot_basic_PRgain,
    pilot_basic_FF,
    pilot_basic_FFgain,

    pilot_wind_gps_wind_offset_deg,
    pilot_wind_P,
    pilot_wind_Pgain,
    pilot_wind_D,
    pilot_wind_Dgain,
    pilot_wind_DD,
    pilot_wind_DDgain,
    pilot_wind_WG,
    pilot_wind_WGgain,

    pilot_absolute_P,
    pilot_absolute_Pgain,
    pilot_absolute_I,
    pilot_absolute_Igain,
    pilot_absolute_D,
    pilot_absolute_Dgain,
    pilot_absolute_FF,
    pilot_absolute_FFgain,

    pilot_rate_D,
    pilot_rate_Dgain,
    pilot_rate_DD,
    pilot_rate_DDgain,
    pilot_rate_FF,
    pilot_rate_FFgain,
    pilot_rate_maxturnrate_deg_s,
    pilot_rate_turnraterate_deg_s2,

    pilot_simple_P,
    pilot_simple_Pgain,
    pilot_simple_I,
    pilot_simple_Igain,
    pilot_simple_D,
    pilot_simple_Dgain,

    pilot_vmg_P,
    pilot_vmg_Pgain,
    pilot_vmg_D,
    pilot_vmg_Dgain,
    pilot_vmg_DD,
    pilot_vmg_DDgain
};

} // namespace pypilot_data_model
