#pragma once

#include <stddef.h>
#include "field_meta.hpp"

namespace pypilot_data_model {

static constexpr FieldMeta field_table[] = {
    {FieldId::ap_enabled, "ap.enabled", "", FieldType::boolean, true, false, false},
    {FieldId::ap_mode, "ap.mode", "", FieldType::mode_enum, true, true, false},
    {FieldId::ap_pilot, "ap.pilot", "", FieldType::pilot_enum, true, true, true},
    {FieldId::ap_heading_deg, "ap.heading", "deg", FieldType::number, false, false, false},
    {FieldId::ap_heading_command_deg, "ap.heading_command", "deg", FieldType::number, true, false, false},
    {FieldId::ap_heading_error_deg, "ap.heading_error", "deg", FieldType::number, false, false, false},
    {FieldId::ap_heading_error_int_deg, "ap.heading_error_int", "deg", FieldType::number, false, false, false},
    {FieldId::ap_heading_command_rate_deg_s, "ap.heading_command_rate", "deg/s", FieldType::number, false, false, false},
    {FieldId::ap_runtime_s, "ap.runtime", "s", FieldType::number, false, false, false},

    {FieldId::imu_heading_deg, "imu.heading", "deg", FieldType::number, false, false, false},
    {FieldId::imu_heading_lowpass_deg, "imu.heading_lowpass", "deg", FieldType::number, false, false, false},
    {FieldId::imu_headingrate_deg_s, "imu.headingrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::imu_headingrate_lowpass_deg_s, "imu.headingrate_lowpass", "deg/s", FieldType::number, false, false, false},
    {FieldId::imu_headingraterate_deg_s2, "imu.headingraterate", "deg/s^2", FieldType::number, false, false, false},
    {FieldId::imu_headingraterate_lowpass_deg_s2, "imu.headingraterate_lowpass", "deg/s^2", FieldType::number, false, false, false},
    {FieldId::imu_pitch_deg, "imu.pitch", "deg", FieldType::number, false, false, false},
    {FieldId::imu_roll_deg, "imu.roll", "deg", FieldType::number, false, false, false},
    {FieldId::imu_heel_deg, "imu.heel", "deg", FieldType::number, false, false, false},
    {FieldId::imu_pitchrate_deg_s, "imu.pitchrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::imu_rollrate_deg_s, "imu.rollrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::imu_fusion_q_pose, "imu.fusionQPose", "", FieldType::quat, false, false, false},

    {FieldId::wind_source, "wind.source", "", FieldType::source_enum, false, false, false},
    {FieldId::wind_direction_deg, "wind.direction", "deg", FieldType::number, false, false, false},
    {FieldId::wind_speed_kn, "wind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::wind_filtered_direction_deg, "wind.filtered_direction", "deg", FieldType::number, false, false, false},
    {FieldId::wind_filtered_speed_kn, "wind.filtered_speed", "kn", FieldType::number, false, false, false},
    {FieldId::wind_offset_deg, "wind.offset", "deg", FieldType::number, true, false, false},
    {FieldId::wind_sensors_height_m, "wind.sensors_height", "m", FieldType::number, true, false, false},
    {FieldId::wind_filter_constant_0_1, "wind.filter_constant", "", FieldType::number, true, true, false},
    {FieldId::wind_filter_factor_0_1, "wind.filter_factor", "", FieldType::number, false, false, false},

    {FieldId::truewind_source, "truewind.source", "", FieldType::source_enum, false, false, false},
    {FieldId::truewind_direction_deg, "truewind.direction", "deg", FieldType::number, false, false, false},
    {FieldId::truewind_speed_kn, "truewind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::truewind_filtered_direction_deg, "truewind.filtered_direction", "deg", FieldType::number, false, false, false},
    {FieldId::truewind_filtered_speed_kn, "truewind.filtered_speed", "kn", FieldType::number, false, false, false},
    {FieldId::truewind_offset_deg, "truewind.offset", "deg", FieldType::number, true, false, false},
    {FieldId::truewind_sensors_height_m, "truewind.sensors_height", "m", FieldType::number, true, false, false},
    {FieldId::truewind_filter_constant_0_1, "truewind.filter_constant", "", FieldType::number, true, true, false},
    {FieldId::truewind_filter_factor_0_1, "truewind.filter_factor", "", FieldType::number, false, false, false},

    {FieldId::gps_source, "gps.source", "", FieldType::source_enum, false, false, false},
    {FieldId::gps_track_deg, "gps.track", "deg", FieldType::number, false, false, false},
    {FieldId::gps_speed_kn, "gps.speed", "kn", FieldType::number, false, false, false},
    {FieldId::gps_declination_deg, "gps.declination", "deg", FieldType::number, false, false, false},
    {FieldId::gps_compass_error_deg, "gps.compass_error", "deg", FieldType::number, false, false, false},

    {FieldId::apb_source, "apb.source", "", FieldType::source_enum, false, false, false},
    {FieldId::apb_track_deg, "apb.track", "deg", FieldType::number, false, false, false},
    {FieldId::apb_xte_nmi, "apb.xte", "nmi", FieldType::number, false, false, false},
    {FieldId::apb_xte_gain_deg_per_nmi, "apb.xte.gain", "deg/nmi", FieldType::number, true, true, false},
    {FieldId::apb_mode_hint, "apb.mode_hint", "", FieldType::mode_enum, false, false, false},
    {FieldId::apb_sender_id, "apb.sender_id", "", FieldType::string_value, false, false, false},

    {FieldId::water_speed_kn, "water.speed", "kn", FieldType::number, false, false, false},
    {FieldId::water_leeway_deg, "water.leeway", "deg", FieldType::number, false, false, false},
    {FieldId::water_current_speed_kn, "water.current.speed", "kn", FieldType::number, false, false, false},
    {FieldId::water_current_direction_deg, "water.current.direction", "deg", FieldType::number, false, false, false},
    {FieldId::water_wind_speed_kn, "water.wind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::water_wind_direction_deg, "water.wind.direction", "deg", FieldType::number, false, false, false},

    {FieldId::rudder_angle_deg, "rudder.angle", "deg", FieldType::number, false, false, false},
    {FieldId::rudder_speed_deg_s, "rudder.speed", "deg/s", FieldType::number, false, false, false},
    {FieldId::rudder_offset_deg, "rudder.offset", "deg", FieldType::number, true, true, false},
    {FieldId::rudder_scale_deg_per_raw, "rudder.scale", "deg/raw", FieldType::number, true, true, false},
    {FieldId::rudder_nonlinearity, "rudder.nonlinearity", "", FieldType::number, true, true, false},
    {FieldId::rudder_range_deg, "rudder.range", "deg", FieldType::number, true, true, false},
    {FieldId::rudder_calibration_state, "rudder.calibration_state", "", FieldType::rudder_calibration_enum, true, false, false},

    {FieldId::servo_command_norm, "servo.command", "", FieldType::number, true, false, false},
    {FieldId::servo_position_command_deg, "servo.position_command", "deg", FieldType::number, true, false, false},
    {FieldId::servo_current_a, "servo.current", "A", FieldType::number, false, false, false},
    {FieldId::servo_current_noise_a, "servo.current.noise", "A", FieldType::number, false, false, false},
    {FieldId::servo_voltage_v, "servo.voltage", "V", FieldType::number, false, false, false},
    {FieldId::servo_controller_temp_c, "servo.controller_temp", "C", FieldType::number, false, false, false},
    {FieldId::servo_motor_temp_c, "servo.motor_temp", "C", FieldType::number, false, false, false},
    {FieldId::servo_engaged, "servo.engaged", "", FieldType::boolean, false, false, false},
    {FieldId::servo_flags, "servo.flags", "", FieldType::number, false, false, false},
    {FieldId::servo_faults, "servo.faults", "", FieldType::number, true, true, false},
    {FieldId::servo_max_current_a, "servo.max_current", "A", FieldType::number, true, false, false},
    {FieldId::servo_period_s, "servo.period", "s", FieldType::number, true, false, true},
    {FieldId::servo_speed_norm, "servo.speed", "", FieldType::number, false, false, false},
    {FieldId::servo_position_deg, "servo.position", "deg", FieldType::number, false, false, false},
    {FieldId::servo_duty_pct, "servo.duty", "%", FieldType::number, false, false, false},
    {FieldId::servo_watts_w, "servo.watts", "W", FieldType::number, false, false, false},
    {FieldId::servo_amp_hours_ah, "servo.amp_hours", "Ah", FieldType::number, true, true, false},

    {FieldId::pilot_basic_P, "ap.pilot.basic.P", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_Pgain, "ap.pilot.basic.Pgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_basic_D, "ap.pilot.basic.D", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_Dgain, "ap.pilot.basic.Dgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_basic_DD, "ap.pilot.basic.DD", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_DDgain, "ap.pilot.basic.DDgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_basic_PR, "ap.pilot.basic.PR", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_PRgain, "ap.pilot.basic.PRgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_basic_FF, "ap.pilot.basic.FF", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_FFgain, "ap.pilot.basic.FFgain", "", FieldType::number, false, false, false},

    {FieldId::pilot_wind_gps_wind_offset_deg, "ap.pilot.wind.gps_wind_offset", "deg", FieldType::number, false, false, false},
    {FieldId::pilot_wind_P, "ap.pilot.wind.P", "", FieldType::number, true, true, true},
    {FieldId::pilot_wind_Pgain, "ap.pilot.wind.Pgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_wind_D, "ap.pilot.wind.D", "", FieldType::number, true, true, true},
    {FieldId::pilot_wind_Dgain, "ap.pilot.wind.Dgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_wind_DD, "ap.pilot.wind.DD", "", FieldType::number, true, true, true},
    {FieldId::pilot_wind_DDgain, "ap.pilot.wind.DDgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_wind_WG, "ap.pilot.wind.WG", "", FieldType::number, true, true, true},
    {FieldId::pilot_wind_WGgain, "ap.pilot.wind.WGgain", "", FieldType::number, false, false, false},

    {FieldId::pilot_absolute_P, "ap.pilot.absolute.P", "", FieldType::number, true, true, true},
    {FieldId::pilot_absolute_Pgain, "ap.pilot.absolute.Pgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_absolute_I, "ap.pilot.absolute.I", "", FieldType::number, true, true, true},
    {FieldId::pilot_absolute_Igain, "ap.pilot.absolute.Igain", "", FieldType::number, false, false, false},
    {FieldId::pilot_absolute_D, "ap.pilot.absolute.D", "", FieldType::number, true, true, true},
    {FieldId::pilot_absolute_Dgain, "ap.pilot.absolute.Dgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_absolute_FF, "ap.pilot.absolute.FF", "", FieldType::number, true, true, true},
    {FieldId::pilot_absolute_FFgain, "ap.pilot.absolute.FFgain", "", FieldType::number, false, false, false},

    {FieldId::pilot_rate_D, "ap.pilot.rate.D", "", FieldType::number, true, true, true},
    {FieldId::pilot_rate_Dgain, "ap.pilot.rate.Dgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_rate_DD, "ap.pilot.rate.DD", "", FieldType::number, true, true, true},
    {FieldId::pilot_rate_DDgain, "ap.pilot.rate.DDgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_rate_FF, "ap.pilot.rate.FF", "", FieldType::number, true, true, true},
    {FieldId::pilot_rate_FFgain, "ap.pilot.rate.FFgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_rate_maxturnrate_deg_s, "ap.pilot.rate.maxturnrate", "deg/s", FieldType::number, true, true, false},
    {FieldId::pilot_rate_turnraterate_deg_s2, "ap.pilot.rate.turnraterate", "deg/s^2", FieldType::number, true, true, true},

    {FieldId::pilot_simple_P, "ap.pilot.simple.P", "", FieldType::number, true, true, true},
    {FieldId::pilot_simple_Pgain, "ap.pilot.simple.Pgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_simple_I, "ap.pilot.simple.I", "", FieldType::number, true, true, true},
    {FieldId::pilot_simple_Igain, "ap.pilot.simple.Igain", "", FieldType::number, false, false, false},
    {FieldId::pilot_simple_D, "ap.pilot.simple.D", "", FieldType::number, true, true, true},
    {FieldId::pilot_simple_Dgain, "ap.pilot.simple.Dgain", "", FieldType::number, false, false, false},

    {FieldId::pilot_vmg_P, "ap.pilot.vmg.P", "", FieldType::number, true, true, true},
    {FieldId::pilot_vmg_Pgain, "ap.pilot.vmg.Pgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_vmg_D, "ap.pilot.vmg.D", "", FieldType::number, true, true, true},
    {FieldId::pilot_vmg_Dgain, "ap.pilot.vmg.Dgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_vmg_DD, "ap.pilot.vmg.DD", "", FieldType::number, true, true, true},
    {FieldId::pilot_vmg_DDgain, "ap.pilot.vmg.DDgain", "", FieldType::number, false, false, false}
};

static constexpr size_t field_table_size = sizeof(field_table) / sizeof(field_table[0]);

} // namespace pypilot_data_model
