#pragma once

#include <stddef.h>
#include "field_meta.hpp"

namespace pypilot_data_model {

static constexpr FieldMeta field_table[] = {
    {FieldId::server_version, "server.version", "", FieldType::string_value, false, false, false},
    {FieldId::server_hostname, "server.hostname", "", FieldType::string_value, false, false, false},
    {FieldId::server_config_dir, "server.config_dir", "", FieldType::string_value, false, true, false},
    {FieldId::server_profile_name, "profile.name", "", FieldType::string_value, true, true, false},
    {FieldId::server_enabled, "server.enabled", "", FieldType::boolean, true, true, false},
    {FieldId::server_persistent, "server.persistent", "", FieldType::boolean, true, true, false},
    {FieldId::server_watchdog_enabled, "server.watchdog", "", FieldType::boolean, true, true, false},
    {FieldId::server_timestamp_s, "server.timestamp", "s", FieldType::number, false, false, false},
    {FieldId::server_uptime_s, "server.uptime", "s", FieldType::number, false, false, false},
    {FieldId::server_monotonic_s, "server.monotonic", "s", FieldType::number, false, false, false},
    {FieldId::server_poll_period_s, "server.poll_period", "s", FieldType::number, false, false, false},
    {FieldId::server_client_count, "server.client_count", "", FieldType::number, false, false, false},
    {FieldId::server_value_count, "server.value_count", "", FieldType::number, false, false, false},
    {FieldId::server_watch_count, "server.watch_count", "", FieldType::number, false, false, false},

    {FieldId::status_health, "status.health", "", FieldType::number, false, false, false},
    {FieldId::status_faults, "status.faults", "", FieldType::number, false, false, false},
    {FieldId::status_warnings, "status.warnings", "", FieldType::number, false, false, false},
    {FieldId::status_uptime_s, "status.uptime", "s", FieldType::number, false, false, false},
    {FieldId::status_loop_period_s, "status.loop_period", "s", FieldType::number, false, false, false},
    {FieldId::status_cpu_load_0_1, "status.cpu_load", "", FieldType::number, false, false, false},
    {FieldId::status_free_memory_bytes, "status.free_memory", "bytes", FieldType::number, false, false, false},
    {FieldId::status_last_error, "status.last_error", "", FieldType::string_value, false, false, false},
    {FieldId::status_last_warning, "status.last_warning", "", FieldType::string_value, false, false, false},

    {FieldId::ap_enabled, "ap.enabled", "", FieldType::boolean, true, false, false},
    {FieldId::ap_mode, "ap.mode", "", FieldType::mode_enum, true, true, false},
    {FieldId::ap_preferred_mode, "ap.preferred_mode", "", FieldType::mode_enum, true, true, false},
    {FieldId::ap_pilot, "ap.pilot", "", FieldType::pilot_enum, true, true, true},
    {FieldId::ap_heading_deg, "ap.heading", "deg", FieldType::number, false, false, false},
    {FieldId::ap_heading_command_deg, "ap.heading_command", "deg", FieldType::number, true, false, false},
    {FieldId::ap_heading_error_deg, "ap.heading_error", "deg", FieldType::number, false, false, false},
    {FieldId::ap_heading_error_int_deg, "ap.heading_error_int", "deg", FieldType::number, false, false, false},
    {FieldId::ap_heading_command_rate_deg_s, "ap.heading_command_rate", "deg/s", FieldType::number, false, false, false},
    {FieldId::ap_runtime_s, "ap.runtime", "s", FieldType::number, false, false, false},

    {FieldId::ap_tack_enabled, "ap.tack.enabled", "", FieldType::boolean, true, false, false},
    {FieldId::ap_tack_state, "ap.tack.state", "", FieldType::number, true, false, false},
    {FieldId::ap_tack_direction, "ap.tack.direction", "", FieldType::number, true, false, false},
    {FieldId::ap_tack_timeout_s, "ap.tack.timeout", "s", FieldType::number, true, true, false},
    {FieldId::ap_tack_delay_s, "ap.tack.delay", "s", FieldType::number, true, true, false},
    {FieldId::ap_tack_angle_deg, "ap.tack.angle", "deg", FieldType::number, true, true, false},
    {FieldId::ap_tack_rate_deg_s, "ap.tack.rate", "deg/s", FieldType::number, true, true, false},
    {FieldId::ap_tack_progress_0_1, "ap.tack.progress", "", FieldType::number, false, false, false},
    {FieldId::ap_tack_command_heading_deg, "ap.tack.command_heading", "deg", FieldType::number, false, false, false},
    {FieldId::ap_tack_start_heading_deg, "ap.tack.start_heading", "deg", FieldType::number, false, false, false},
    {FieldId::ap_tack_target_heading_deg, "ap.tack.target_heading", "deg", FieldType::number, false, false, false},

    {FieldId::pilot_command_source, "ap.command.source", "", FieldType::number, false, false, false},
    {FieldId::pilot_command_heading_deg, "ap.command.heading", "deg", FieldType::number, true, false, false},
    {FieldId::pilot_command_heading_rate_deg_s, "ap.command.heading_rate", "deg/s", FieldType::number, true, false, false},
    {FieldId::pilot_command_servo_norm, "ap.command.servo", "", FieldType::number, true, false, false},
    {FieldId::pilot_command_servo_position_deg, "ap.command.servo_position", "deg", FieldType::number, true, false, false},
    {FieldId::pilot_output_command_norm, "ap.output.command", "", FieldType::number, false, false, false},
    {FieldId::pilot_output_heading_error_deg, "ap.output.heading_error", "deg", FieldType::number, false, false, false},
    {FieldId::pilot_output_desired_heading_deg, "ap.output.desired_heading", "deg", FieldType::number, false, false, false},
    {FieldId::pilot_output_desired_heading_rate_deg_s, "ap.output.desired_heading_rate", "deg/s", FieldType::number, false, false, false},
    {FieldId::pilot_output_saturated_command_norm, "ap.output.saturated_command", "", FieldType::number, false, false, false},
    {FieldId::pilot_output_feed_forward_norm, "ap.output.feed_forward", "", FieldType::number, false, false, false},
    {FieldId::pilot_output_proportional_norm, "ap.output.proportional", "", FieldType::number, false, false, false},
    {FieldId::pilot_output_derivative_norm, "ap.output.derivative", "", FieldType::number, false, false, false},
    {FieldId::pilot_output_integral_norm, "ap.output.integral", "", FieldType::number, false, false, false},
    {FieldId::pilot_output_saturated, "ap.output.saturated", "", FieldType::boolean, false, false, false},
    {FieldId::pilot_output_fault, "ap.output.fault", "", FieldType::boolean, false, false, false},
    {FieldId::pilot_output_active_name, "ap.output.active_pilot", "", FieldType::string_value, false, false, false},

    {FieldId::imu_state_enabled, "imu.enabled", "", FieldType::boolean, true, true, false},
    {FieldId::imu_state_present, "imu.present", "", FieldType::boolean, false, false, false},
    {FieldId::imu_state_healthy, "imu.healthy", "", FieldType::boolean, false, false, false},
    {FieldId::imu_state_device, "imu.device", "", FieldType::string_value, false, false, false},
    {FieldId::imu_state_driver, "imu.driver", "", FieldType::string_value, false, false, false},
    {FieldId::imu_state_rate_hz, "imu.rate", "Hz", FieldType::number, false, false, false},
    {FieldId::imu_state_dt_s, "imu.dt", "s", FieldType::number, false, false, false},
    {FieldId::imu_state_sample_count, "imu.sample_count", "", FieldType::number, false, false, false},
    {FieldId::imu_state_drop_count, "imu.drop_count", "", FieldType::number, false, false, false},
    {FieldId::imu_state_error_count, "imu.error_count", "", FieldType::number, false, false, false},
    {FieldId::imu_calibration_state, "imu.calibration.state", "", FieldType::number, false, true, false},
    {FieldId::imu_calibration_accel_valid, "imu.calibration.accel.valid", "", FieldType::boolean, false, true, false},
    {FieldId::imu_calibration_compass_valid, "imu.calibration.compass.valid", "", FieldType::boolean, false, true, false},
    {FieldId::imu_calibration_gyro_valid, "imu.calibration.gyro.valid", "", FieldType::boolean, false, true, false},
    {FieldId::imu_calibration_heading_offset_deg, "imu.calibration.heading_offset", "deg", FieldType::number, true, true, false},
    {FieldId::imu_calibration_compass_field_strength, "imu.calibration.compass.field_strength", "", FieldType::number, false, false, false},
    {FieldId::imu_calibration_compass_inclination_deg, "imu.calibration.compass.inclination", "deg", FieldType::number, false, false, false},
    {FieldId::imu_calibration_progress_0_1, "imu.calibration.progress", "", FieldType::number, false, false, false},

    {FieldId::imu_heading_deg, "imu.heading", "deg", FieldType::number, false, false, false},
    {FieldId::imu_heading_lowpass_deg, "imu.heading_lowpass", "deg", FieldType::number, false, false, false},
    {FieldId::imu_headingrate_deg_s, "imu.headingrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::imu_headingrate_lowpass_deg_s, "imu.headingrate_lowpass", "deg/s", FieldType::number, false, false, false},
    {FieldId::imu_headingraterate_deg_s2, "imu.headingraterate", "deg/s^2", FieldType::number, false, false, false},
    {FieldId::imu_headingraterate_lowpass_deg_s2, "imu.headingraterate_lowpass", "deg/s^2", FieldType::number, false, false, false},
    {FieldId::imu_pitch_deg, "imu.pitch", "deg", FieldType::number, false, false, false},
    {FieldId::imu_roll_deg, "imu.roll", "deg", FieldType::number, false, false, false},
    {FieldId::imu_heel_deg, "imu.heel", "deg", FieldType::number, false, false, false},
    {FieldId::imu_pitchrate_deg_s, "imu.pitchrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::imu_rollrate_deg_s, "imu.rollrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::imu_fusion_q_pose, "imu.fusionQPose", "", FieldType::quat, false, false, false},

    {FieldId::wind_source, "wind.source", "", FieldType::source_enum, false, false, false},
    {FieldId::wind_direction_deg, "wind.direction", "deg", FieldType::number, false, false, false},
    {FieldId::wind_speed_kn, "wind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::wind_filtered_direction_deg, "wind.filtered_direction", "deg", FieldType::number, false, false, false},
    {FieldId::wind_filtered_speed_kn, "wind.filtered_speed", "kn", FieldType::number, false, false, false},
    {FieldId::wind_offset_deg, "wind.offset", "deg", FieldType::number, true, false, false},
    {FieldId::wind_sensors_height_m, "wind.sensors_height", "m", FieldType::number, true, false, false},
    {FieldId::wind_filter_constant_0_1, "wind.filter_constant", "", FieldType::number, true, true, false},
    {FieldId::wind_filter_factor_0_1, "wind.filter_factor", "", FieldType::number, false, false, false},

    {FieldId::truewind_source, "truewind.source", "", FieldType::source_enum, false, false, false},
    {FieldId::truewind_direction_deg, "truewind.direction", "deg", FieldType::number, false, false, false},
    {FieldId::truewind_speed_kn, "truewind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::truewind_filtered_direction_deg, "truewind.filtered_direction", "deg", FieldType::number, false, false, false},
    {FieldId::truewind_filtered_speed_kn, "truewind.filtered_speed", "kn", FieldType::number, false, false, false},
    {FieldId::truewind_offset_deg, "truewind.offset", "deg", FieldType::number, true, false, false},
    {FieldId::truewind_sensors_height_m, "truewind.sensors_height", "m", FieldType::number, true, false, false},
    {FieldId::truewind_filter_constant_0_1, "truewind.filter_constant", "", FieldType::number, true, true, false},
    {FieldId::truewind_filter_factor_0_1, "truewind.filter_factor", "", FieldType::number, false, false, false},

    {FieldId::gps_source, "gps.source", "", FieldType::source_enum, false, false, false},
    {FieldId::gps_timestamp_s, "gps.timestamp", "s", FieldType::number, false, false, false},
    {FieldId::gps_track_deg, "gps.track", "deg", FieldType::number, false, false, false},
    {FieldId::gps_speed_kn, "gps.speed", "kn", FieldType::number, false, false, false},
    {FieldId::gps_declination_deg, "gps.declination", "deg", FieldType::number, false, false, false},
    {FieldId::gps_compass_error_deg, "gps.compass_error", "deg", FieldType::number, false, false, false},

    {FieldId::apb_source, "apb.source", "", FieldType::source_enum, false, false, false},
    {FieldId::apb_track_deg, "apb.track", "deg", FieldType::number, false, false, false},
    {FieldId::apb_xte_nmi, "apb.xte", "nmi", FieldType::number, false, false, false},
    {FieldId::apb_xte_gain_deg_per_nmi, "apb.xte.gain", "deg/nmi", FieldType::number, true, true, false},
    {FieldId::apb_mode_hint, "apb.mode_hint", "", FieldType::mode_enum, false, false, false},
    {FieldId::apb_sender_id, "apb.sender_id", "", FieldType::string_value, false, false, false},

    {FieldId::water_speed_kn, "water.speed", "kn", FieldType::number, false, false, false},
    {FieldId::water_leeway_deg, "water.leeway", "deg", FieldType::number, false, false, false},
    {FieldId::water_current_speed_kn, "water.current.speed", "kn", FieldType::number, false, false, false},
    {FieldId::water_current_direction_deg, "water.current.direction", "deg", FieldType::number, false, false, false},
    {FieldId::water_wind_speed_kn, "water.wind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::water_wind_direction_deg, "water.wind.direction", "deg", FieldType::number, false, false, false},

    {FieldId::rudder_angle_deg, "rudder.angle", "deg", FieldType::number, false, false, false},
    {FieldId::rudder_speed_deg_s, "rudder.speed", "deg/s", FieldType::number, false, false, false},
    {FieldId::rudder_offset_deg, "rudder.offset", "deg", FieldType::number, true, true, false},
    {FieldId::rudder_scale_deg_per_raw, "rudder.scale", "deg/raw", FieldType::number, true, true, false},
    {FieldId::rudder_nonlinearity, "rudder.nonlinearity", "", FieldType::number, true, true, false},
    {FieldId::rudder_range_deg, "rudder.range", "deg", FieldType::number, true, true, false},
    {FieldId::rudder_calibration_state, "rudder.calibration_state", "", FieldType::rudder_calibration_enum, true, false, false},

    {FieldId::servo_command_norm, "servo.command", "", FieldType::number, true, false, false},
    {FieldId::servo_position_command_deg, "servo.position_command", "deg", FieldType::number, true, false, false},
    {FieldId::servo_current_a, "servo.current", "A", FieldType::number, false, false, false},
    {FieldId::servo_current_noise_a, "servo.current.noise", "A", FieldType::number, false, false, false},
    {FieldId::servo_voltage_v, "servo.voltage", "V", FieldType::number, false, false, false},
    {FieldId::servo_controller_temp_c, "servo.controller_temp", "C", FieldType::number, false, false, false},
    {FieldId::servo_motor_temp_c, "servo.motor_temp", "C", FieldType::number, false, false, false},
    {FieldId::servo_engaged, "servo.engaged", "", FieldType::boolean, false, false, false},
    {FieldId::servo_flags, "servo.flags", "", FieldType::number, false, false, false},
    {FieldId::servo_faults, "servo.faults", "", FieldType::number, true, true, false},
    {FieldId::servo_max_current_a, "servo.max_current", "A", FieldType::number, true, false, false},
    {FieldId::servo_period_s, "servo.period", "s", FieldType::number, true, false, true},
    {FieldId::servo_speed_norm, "servo.speed", "", FieldType::number, false, false, false},
    {FieldId::servo_position_deg, "servo.position", "deg", FieldType::number, false, false, false},
    {FieldId::servo_duty_pct, "servo.duty", "%", FieldType::number, false, false, false},
    {FieldId::servo_watts_w, "servo.watts", "W", FieldType::number, false, false, false},
    {FieldId::servo_amp_hours_ah, "servo.amp_hours", "Ah", FieldType::number, true, true, false},

    {FieldId::servo_telemetry_state, "servo.telemetry.state", "", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_command_norm, "servo.telemetry.command", "", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_raw_command_norm, "servo.telemetry.raw_command", "", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_position_deg, "servo.telemetry.position", "deg", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_position_command_deg, "servo.telemetry.position_command", "deg", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_speed_norm, "servo.telemetry.speed", "", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_duty_pct, "servo.telemetry.duty", "%", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_voltage_v, "servo.telemetry.voltage", "V", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_current_a, "servo.telemetry.current", "A", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_current_noise_a, "servo.telemetry.current_noise", "A", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_watts_w, "servo.telemetry.watts", "W", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_controller_temp_c, "servo.telemetry.controller_temp", "C", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_motor_temp_c, "servo.telemetry.motor_temp", "C", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_rudder_feedback_deg, "servo.telemetry.rudder_feedback", "deg", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_packet_count, "servo.telemetry.packet_count", "", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_bad_packet_count, "servo.telemetry.bad_packet_count", "", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_timeout_count, "servo.telemetry.timeout_count", "", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_reboot_count, "servo.telemetry.reboot_count", "", FieldType::number, false, false, false},

    {FieldId::pilot_basic_P, "ap.pilot.basic.P", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_Pgain, "ap.pilot.basic.Pgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_basic_D, "ap.pilot.basic.D", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_Dgain, "ap.pilot.basic.Dgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_basic_DD, "ap.pilot.basic.DD", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_DDgain, "ap.pilot.basic.DDgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_basic_PR, "ap.pilot.basic.PR", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_PRgain, "ap.pilot.basic.PRgain", "", FieldType::number, false, false, false},
    {FieldId::pilot_basic_FF, "ap.pilot.basic.FF", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_FFgain, "ap.pilot.basic.FFgain", "", FieldType::number, false, false, false},

    {FieldId::runtime_last_publish_period_s, "runtime.publish_period", "s", FieldType::number, false, false, false},
    {FieldId::runtime_published_value_count, "runtime.published_value_count", "", FieldType::number, false, false, false},
    {FieldId::runtime_dropped_value_count, "runtime.dropped_value_count", "", FieldType::number, false, false, false}
};

static constexpr size_t field_table_size = sizeof(field_table) / sizeof(field_table[0]);

} // namespace pypilot_data_model
